name: Create apache-nifi-s3 docker container

on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - master

jobs:
  build-pypi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - run: python -m pip install --upgrade pip
      - run: python -m pip install --upgrade setuptools wheel
      - run: python -m pip install --upgrade twine
      - run: python setup.py sdist bdist_wheel
      - run: twine upload dist/*
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}